variable "sql_server_name" {}
variable "rg_name" {}
variable "location" {}
variable "sql_server_version" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "sql_db_name" {}
variable "db_edition" {}
variable "db_collation" {}
variable "db_auto_pause_delay" {}
variable "db_min_capacity" {}
variable "db_max_capacity" {}
