name: Terraform-apply

on:
  push:
    branches:
      - 'terraform'
    paths:
      - 'terraform/**'

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Azure Login
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: |
      #       {
      #         "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
      #         "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
      #         "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
      #         "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      #       }
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/
        run: terraform apply -auto-approve